spring.application.name=rabbitmq-ms-consumer2-sumativa
server.port=8083

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Líneas de Debug para monitoreo en consola
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.web=DEBUG